### ISSUE TITLE
Expose extra port for rcon

### ISSUE THREAD

**Issue by yhesse** [DArtagan/docker-spigot#1]
Hi, can you expose an extra port so I can connect with rcon? Thanks!

**Comment by DArtagan** [comment]
RCON was new to me, thanks.

Why do you specifically need a port exposed? Would running the container with -p be adequate for your needs?

**Comment by yhesse** [comment]
I use docker on my server to launch the container so I cannot add -p (or I don't know how :p)
Rcon cannot bind to the same port as minecraft itself.

**Comment by yhesse** [comment]
This is my screen: 
https://yveshessels.stackstorage.com/s/rQLkH7MKKVA9BWB

**Comment by DArtagan** [comment]
I see. When I get a chance, I'll expose a port for RCON.

Out of general curiosity, what company is the host for your Docker server?

**Comment by yhesse** [comment]
https://www.transip.be/

**Comment by DArtagan** [comment]
I've made a new build to expose an extra port.  Let me know if it works for you.

**Comment by yhesse** [comment]
You'r a GOD! it works, thanks!
